extends SceneTree
## Converts generated magenta sheets to alpha and records anatomical anchors.
## No sprite drawing, interpolation, per-frame scaling or runtime image processing.
const ROOT := "res://assets/lia_expanded/"

func _initialize() -> void:
	var data := {"walk": [], "idle": [], "scales": {}, "directions": ["down", "left", "right", "up"]}
	for name in ["walk", "idle"]:
		var img := Image.load_from_file(ROOT + "source_" + name + ".png")
		assert(img != null, "Missing source sheet")
		img.convert(Image.FORMAT_RGBA8)
		for y in img.get_height():
			for x in img.get_width():
				var c := img.get_pixel(x, y)
				if minf(c.r, c.b) > .03 and c.r > c.g * 1.4 and c.b > c.g * 1.4:
					img.set_pixel(x, y, Color.TRANSPARENT)
		var rows: Array[int] = []
		rows.resize(img.get_height())
		for y in img.get_height():
			for x in img.get_width():
				if img.get_pixel(x, y).a > .5: rows[y] += 1
		var bands := _bands(rows)
		assert(bands.size() == 4, "Expected four directional rows")
		for direction in 4:
			var band := bands[direction]
			var columns: Array[int] = []
			columns.resize(img.get_width())
			for x in img.get_width():
				for y in range(band.x, band.y):
					if img.get_pixel(x, y).a > .5: columns[x] += 1
			var spans := _bands(columns)
			assert(spans.size() == (8 if name == "walk" else 4), "Unexpected number of frames")
			var frames := []
			for span in spans:
				var raw := Rect2i(span.x, band.x, span.y - span.x, band.y - band.x)
				var bounds := img.get_region(raw).get_used_rect()
				bounds.position += raw.position
				var anchor := _anchor(img, bounds)
				var muzzle := _muzzle(img, bounds, direction)
				frames.append({"region": [bounds.position.x, bounds.position.y, bounds.size.x, bounds.size.y],
					"anchor": [anchor.x, anchor.y], "muzzle": [muzzle.x, muzzle.y]})
			data[name].append(frames)
		# One scale for the whole sheet: no resizing by frame or by facing.
		var heights := []
		for frame in data[name][0]: heights.append(frame.region[3])
		heights.sort()
		data.scales[name] = 48.0 / float(heights[heights.size() / 2])
		assert(img.save_png(ROOT + name + ".png") == OK)
	var json := JSON.stringify(data, "\t")
	FileAccess.open(ROOT + "frames.json", FileAccess.WRITE).store_string(json)
	FileAccess.open(ROOT + "frames.gd", FileAccess.WRITE).store_string("extends RefCounted\n# Generated by tools/import_expanded_lia.gd. Coordinates are source pixels.\nconst DATA = " + json + "\n")
	print("LIA_EXPANDED_IMPORT_OK: 32 walk + 16 idle, scales=", data.scales)
	quit()

func _anchor(img: Image, bounds: Rect2i) -> Vector2i:
	# Navy trousers just below the belt locate the pelvis; rifle extents are ignored.
	var samples: Array[int] = []
	for y in range(bounds.position.y + int(bounds.size.y * .73), bounds.position.y + int(bounds.size.y * .79)):
		for x in range(bounds.position.x, bounds.end.x):
			var c := img.get_pixel(x, y)
			if c.a > .5 and c.b > c.r * 1.3 and c.g > c.r * 1.2 and c.g < .43 and c.g < c.b * 1.45:
				samples.append(x)
	assert(not samples.is_empty(), "Cannot find pelvis")
	var centre := 0.0
	for x in samples: centre += x
	return Vector2i(roundi(centre / samples.size()), bounds.end.y)

func _muzzle(img: Image, bounds: Rect2i, direction: int) -> Vector2i:
	var cyan: Array[Vector2i] = []
	for y in range(bounds.position.y, bounds.end.y):
		for x in range(bounds.position.x, bounds.end.x):
			var c := img.get_pixel(x, y)
			if c.a > .5 and c.g > .65 and c.b > .65 and c.r < .70 and c.b > c.r * 1.35:
				cyan.append(Vector2i(x, y))
	assert(not cyan.is_empty(), "Cannot find cyan emitter")
	var axis: Vector2i = [Vector2i.DOWN, Vector2i.LEFT, Vector2i.RIGHT, Vector2i.UP][direction]
	var furthest := -100000
	for p in cyan: furthest = maxi(furthest, p.x * axis.x + p.y * axis.y)
	var total := Vector2.ZERO
	var count := 0
	for p in cyan:
		if p.x * axis.x + p.y * axis.y >= furthest - 3:
			total += Vector2(p)
			count += 1
	var centre := Vector2i((total / count).round())
	# Move the point from the lit core to the outer end of the emitter.
	if axis.x != 0: centre.x = (furthest + 2) * axis.x
	else: centre.y = (furthest + 2) * axis.y
	return centre

func _bands(counts: Array[int]) -> Array[Vector2i]:
	var result: Array[Vector2i] = []
	var start := -1
	for i in counts.size():
		if counts[i] > 2 and start < 0: start = i
		elif counts[i] <= 2 and start >= 0:
			var next := i
			while next < mini(i + 8, counts.size()) and counts[next] <= 2: next += 1
			if next >= mini(i + 8, counts.size()):
				result.append(Vector2i(start, i))
				start = -1
	if start >= 0: result.append(Vector2i(start, counts.size()))
	return result
