extends SceneTree
## Deterministic atlas extraction: no redraw, resampling or replacement art.
const ROOT := "res://assets/lia_official/"

func _initialize() -> void:
	var manifest := {"walk": [], "actions": [], "scale": 0.2}
	for source in ["walk", "actions"]:
		var img := Image.load_from_file(ROOT + "source_" + source + ".png")
		if img == null:
			quit(1)
			return
		img.convert(Image.FORMAT_RGBA8)
		var rows: Array[int] = []
		rows.resize(img.get_height())
		for y in img.get_height():
			for x in img.get_width():
				var c := img.get_pixel(x, y)
				if minf(c.r, c.b) > 0.03 and c.r > c.g * 1.4 and c.b > c.g * 1.4:
					img.set_pixel(x, y, Color(0, 0, 0, 0))
				else:
					rows[y] += 1
		var bands := _bands(rows)
		assert(bands.size() == 4, "Expected four separated rows")
		for band in bands:
			var cols: Array[int] = []
			cols.resize(img.get_width())
			for x in img.get_width():
				for y in range(band.x, band.y):
					if img.get_pixel(x, y).a > 0:
						cols[x] += 1
			var spans := _bands(cols)
			assert(spans.size() == 4, "Expected four separated figures")
			var frames: Array = []
			for span in spans:
				var bounds := Rect2i(span.x, band.x, span.y - span.x, band.y - band.x)
				var used := img.get_region(bounds).get_used_rect()
				used.position += bounds.position
				frames.append([used.position.x, used.position.y, used.size.x, used.size.y])
			manifest[source].append(frames)
		assert(img.save_png(ROOT + source + ".png") == OK)
	# Same scale for all poses, anchored at feet +18 from simulation centre.
	var idle_height: int = manifest.actions[0][0][3]
	manifest.scale = 48.0 / idle_height
	var file := FileAccess.open(ROOT + "frames.json", FileAccess.WRITE)
	file.store_string(JSON.stringify(manifest, "\t"))
	file.close()
	var resource := FileAccess.open(ROOT + "frames.gd", FileAccess.WRITE)
	resource.store_string("extends RefCounted\n# Generated by tools/import_official_lia.gd.\nconst DATA = " + JSON.stringify(manifest, "\t") + "\n")
	resource.close()
	print("LIA_IMPORT_OK: 16 walk + 16 action poses; scale=", manifest.scale)
	quit()

func _bands(counts: Array[int]) -> Array[Vector2i]:
	var result: Array[Vector2i] = []
	var start := -1
	for i in counts.size():
		if counts[i] > 2 and start < 0:
			start = i
		elif counts[i] <= 2 and start >= 0:
			# Small antialiasing/isolated-pixel gaps do not split a figure.
			var next := i
			while next < mini(i + 8, counts.size()) and counts[next] <= 2:
				next += 1
			if next >= mini(i + 8, counts.size()):
				result.append(Vector2i(start, i))
				start = -1
	if start >= 0:
		result.append(Vector2i(start, counts.size()))
	return result
