extends SceneTree
## Slice generated alpha atlases; preserve source pixels and shared pose scale.
func _initialize() -> void:
	var data := {}
	for kind in ["scout", "sentry", "rammer", "boss"]:
		var path: String = "res://assets/enemies/" + kind + ".png"
		if not FileAccess.file_exists(path):
			push_error("Missing enemy atlas: " + path)
			quit(1)
			return
		var source := Image.load_from_file(path)
		var bounds := _sprite_bounds(source)
		var widest := 1
		var tallest := 1
		for i in 16:
			var rect: Rect2i = bounds[i]
			assert(rect.has_area(), "All 16 directional frames must be present")
			widest = maxi(widest, rect.size.x)
			tallest = maxi(tallest, rect.size.y)
		var size: float = {"scout": 49.0, "sentry": 54.0, "rammer": 56.0, "boss": 108.0}[kind]
		var scale_value := size / maxf(widest, tallest)
		var frames: Array = []
		for i in 16:
			var region := bounds[i]
			var anchor := Vector2(region.position.x + region.size.x * .5, region.end.y)
			var core := Vector2.ZERO
			var score := 0.0
			for y in range(region.position.y, region.end.y):
				for x in range(region.position.x, region.end.x):
					var color := source.get_pixel(x, y)
					var strength := color.r + color.b - color.g * 2.0
					if color.a > .8 and color.r > .65 and color.b > .45 and color.g < .6 and strength > score:
						score = strength
						core = (Vector2(x, y) - anchor) * scale_value
			var rect := Rect2((Vector2(region.position) - anchor) * scale_value, Vector2(region.size) * scale_value)
			frames.append({"region": [region.position.x, region.position.y, region.size.x, region.size.y],
				"rect": [rect.position.x, rect.position.y, rect.size.x, rect.size.y], "core": [core.x, core.y], "has_core": score > 0.0})
		data[kind] = {"frames": frames, "scale": scale_value, "size": [source.get_width(), source.get_height()]}
	var json := JSON.stringify(data, "\t")
	FileAccess.open("res://assets/enemies/frames.json", FileAccess.WRITE).store_string(json)
	FileAccess.open("res://assets/enemies/frames.gd", FileAccess.WRITE).store_string("extends RefCounted\n# Generated by tools/import_enemy_art.gd.\nconst DATA = " + json + "\n")
	print("ENEMY_ATLASES_OK: 64 frames; original alpha preserved")
	quit()

func _sprite_bounds(source: Image) -> Array[Rect2i]:
	# Use the largest connected silhouette per grid cell. Tiny alpha specks and
	# a limb crossing a nominal cell edge must not change the character pivot.
	var width := source.get_width()
	var height := source.get_height()
	var mask := PackedByteArray()
	mask.resize(width * height)
	for y in height:
		for x in width:
			mask[y * width + x] = 1 if source.get_pixel(x, y).a > .55 else 0
	var bounds: Array[Rect2i] = []
	bounds.resize(16)
	var counts := PackedInt32Array()
	counts.resize(16)
	for seed in mask.size():
		if mask[seed] == 0: continue
		var queue: Array[int] = [seed]
		mask[seed] = 0
		var cursor := 0
		var low := Vector2i(seed % width, seed / width)
		var high := low
		while cursor < queue.size():
			var p := Vector2i(queue[cursor] % width, queue[cursor] / width)
			cursor += 1
			low.x = mini(low.x, p.x)
			low.y = mini(low.y, p.y)
			high.x = maxi(high.x, p.x)
			high.y = maxi(high.y, p.y)
			for dy in range(-1, 2):
				for dx in range(-1, 2):
					var n := p + Vector2i(dx, dy)
					if n.x < 0 or n.y < 0 or n.x >= width or n.y >= height: continue
					var index := n.y * width + n.x
					if mask[index] != 0:
						mask[index] = 0
						queue.append(index)
		var rect := Rect2i(low, high - low + Vector2i.ONE)
		var center := rect.get_center()
		var cell := mini(3, center.y * 4 / height) * 4 + mini(3, center.x * 4 / width)
		if queue.size() > counts[cell]:
			counts[cell] = queue.size()
			bounds[cell] = rect
	return bounds
