extends SceneTree
## Deterministic packaging of the authored 24-heading sprite sheets.
const ROOT := "res://assets/lia_directional/"

func _initialize() -> void:
	var data := {"directions": 24, "step_degrees": 15, "walk": [], "idle": [], "scales": {}, "sheets": []}
	for i in 24:
		data.walk.append([])
		data.idle.append([])
	var names := ["idle", "blink"]
	for i in 8: names.append("walk%d" % i)
	var source_size := Vector2i.ZERO
	for sheet in names:
		var img := Image.load_from_file(ROOT + "source_" + sheet + ".png")
		assert(img != null, "Missing authored sheet: " + sheet)
		if source_size == Vector2i.ZERO: source_size = img.get_size()
		assert(img.get_size() == source_size, "All animation sources must retain the same layout and resolution")
		img.convert(Image.FORMAT_RGBA8)
		for y in img.get_height():
			for x in img.get_width():
				var c := img.get_pixel(x, y)
				if minf(c.r, c.b) > .03 and c.r > c.g * 1.4 and c.b > c.g * 1.4:
					img.set_pixel(x, y, Color.TRANSPARENT)
		var counts: Array[int] = []
		counts.resize(img.get_height())
		for y in img.get_height():
			for x in img.get_width():
				if img.get_pixel(x, y).a > .5: counts[y] += 1
		var rows := _bands(counts)
		assert(rows.size() == 4, "Four rows required: " + sheet)
		var frames := []
		for row in 4:
			var band := rows[row]
			var columns: Array[int] = []
			columns.resize(img.get_width())
			for x in img.get_width():
				for y in range(band.x, band.y):
					if img.get_pixel(x, y).a > .5: columns[x] += 1
			var spans := _bands(columns)
			assert(spans.size() == 6, "Six columns required: " + sheet)
			for col in 6:
				var span := spans[col]
				var raw := Rect2i(span.x, band.x, span.y - span.x, band.y - band.x)
				var bounds := img.get_region(raw).get_used_rect()
				bounds.position += raw.position
				var direction := row * 6 + col
				var anchor := _anchor(img, bounds)
				if sheet != "idle":
					# Use the neutral anatomical centre, not whichever leg happens to
					# extend farther in this gait phase. The source grids are aligned.
					anchor.x = int(data.idle[direction][0].anchor[0])
				var muzzle := _muzzle(img, bounds, direction)
				frames.append({"sheet": sheet, "region": [bounds.position.x, bounds.position.y, bounds.size.x, bounds.size.y],
					"anchor": [anchor.x, anchor.y], "muzzle": [muzzle.x, muzzle.y]})
		# The exact same scale for all angles AND phases. Retain authored body bob.
		data.scales[sheet] = 48.0 / float(frames[6].region[3]) if sheet == "idle" else data.scales.idle
		data.sheets.append(sheet)
		for direction in 24:
			if sheet.begins_with("walk"):
				data.walk[direction].append(frames[direction])
			else:
				data.idle[direction].append(frames[direction])
		assert(img.save_png(ROOT + sheet + ".png") == OK)
	var json := JSON.stringify(data, "\t")
	FileAccess.open(ROOT + "frames.json", FileAccess.WRITE).store_string(json)
	FileAccess.open(ROOT + "frames.gd", FileAccess.WRITE).store_string("extends RefCounted\n# Generated by tools/import_directional_lia.gd. Screen angles clockwise from right.\nconst DATA = " + json + "\n")
	print("LIA_DIRECTIONAL_IMPORT_OK: 24 headings, 192 walk + 48 idle/blink sprites")
	quit()

func _anchor(img: Image, bounds: Rect2i) -> Vector2i:
	var xs: Array[int] = []
	for y in range(bounds.end.y - int(bounds.size.y * .27), bounds.end.y - int(bounds.size.y * .21)):
		for x in range(bounds.position.x, bounds.end.x):
			var c := img.get_pixel(x, y)
			if c.a > .5 and c.b > c.r * 1.3 and c.g > c.r * 1.2 and c.g < .43 and c.g < c.b * 1.45:
				xs.append(x)
	assert(not xs.is_empty(), "Cannot find navy trousers")
	var total := 0.0
	for x in xs: total += x
	return Vector2i(roundi(total / xs.size()), bounds.end.y)

func _muzzle(img: Image, bounds: Rect2i, direction: int) -> Vector2i:
	var aim := Vector2.RIGHT.rotated(deg_to_rad(direction * 15.0))
	var cyan: Array[Vector2] = []
	var furthest := -INF
	for y in range(bounds.position.y, bounds.end.y):
		for x in range(bounds.position.x, bounds.end.x):
			var c := img.get_pixel(x, y)
			if c.a > .5 and c.g > .65 and c.b > .65 and c.r < .70 and c.b > c.r * 1.35:
				var p := Vector2(x, y)
				cyan.append(p)
				furthest = maxf(furthest, p.dot(aim))
	assert(not cyan.is_empty(), "Cannot find cyan emitter")
	var total := Vector2.ZERO
	var count := 0
	for p in cyan:
		if p.dot(aim) >= furthest - 3:
			total += p
			count += 1
	return Vector2i((total / count + aim * 2).round())

func _bands(counts: Array[int]) -> Array[Vector2i]:
	var result: Array[Vector2i] = []
	var start := -1
	for i in counts.size():
		if counts[i] > 2 and start < 0: start = i
		elif counts[i] <= 2 and start >= 0:
			var next := i
			while next < mini(i + 8, counts.size()) and counts[next] <= 2: next += 1
			if next >= mini(i + 8, counts.size()):
				result.append(Vector2i(start, i))
				start = -1
	if start >= 0: result.append(Vector2i(start, counts.size()))
	return result
